apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
  labels:
    app: ubuntu
spec:
  containers:
  - image: pzoli77/mydevcontainer:1.0 #gradle:jdk17
    imagePullPolicy: Always
    name: ubuntu
    volumeMounts:
      - mountPath: "/home/pzoli/development"
        name: devroot
      - mountPath: "/home/pzoli/.cache"
        name: cache
      - mountPath: "/home/pzoli/.config"
        name: config
      - mountPath: "/home/pzoli/.dotnet"
        name: dotnet
      - mountPath: "/home/pzoli/.gradle"
        name: gradle
      - mountPath: "/home/pzoli/.java"
        name: java
      - mountPath: "/home/pzoli/.local"
        name: local
      - mountPath: "/home/pzoli/.redhat"
        name: redhat
      - mountPath: "/home/pzoli/.vscode-server"
        name: vscode-server
  restartPolicy: Always
  volumes:
  - name: devroot
    hostPath:
      path: /home/pzoli/development/volumes/devroot
  - name: cache
    hostPath:
      path: /home/pzoli/development/volumes/cache
  - name: config
    hostPath:
      path: /home/pzoli/development/volumes/config
  - name: dotnet
    hostPath:
      path: /home/pzoli/development/volumes/dotnet
  - name: gradle
    hostPath:
      path: /home/pzoli/development/volumes/gradle
  - name: java
    hostPath:
      path: /home/pzoli/development/volumes/java
  - name: local
    hostPath:
      path: /home/pzoli/development/volumes/local
  - name: redhat
    hostPath:
      path: /home/pzoli/development/volumes/redhat
  - name: vscode-server
    hostPath:
      path: /home/pzoli/development/volumes/vscode-server
